### ISSUE TITLE
Variability in shelf-to-vial HT coefficient

### ISSUE THREAD

**Issue by ltdeck** [SPL-ethz/snow#13]
```
from ethz_snow.snowflake import Snowflake
d = {"int": 20, "ext": 20, "s0": 20, "s_sigma_rel": 0}
S = Snowflake(storeStates='all',N_vials=(7,7,1),k=d)
S.run()
S.k
```

When manually adjusting the heat transfer parameters, the effect on the 'shelf' parameters in k is unclear. Setting s_sigma_rel to 0 or to a value higher than 0.1 has no significant impact. Also, when increasing s0 to 2000, the absolute difference between s0 and the 'shelf' parameters remains the same, while it should increase since it is defined in relation to s0.

![bug1](https://user-images.githubusercontent.com/83716040/119230691-aa449880-bb1d-11eb-9d57-57579534ab03.PNG)
![bug1a](https://user-images.githubusercontent.com/83716040/119230695-ac0e5c00-bb1d-11eb-8c1a-ccca5fe7d7a2.PNG)

**Comment by ltdeck** [comment]
![bug1b](https://user-images.githubusercontent.com/83716040/119342218-0847bc00-bc95-11eb-8455-5c789a41dac8.PNG)

I think I found the problem. In line 813, the random term is just directly drawn from the normal distribution, but not multiplied with s_sigma_rel. However, I did not figure out yet why it still draws a random number even in case s_sigma_rel = 0.

**Comment by bizzinho** [comment]
Hey @ltdeck , problem is fixed.

It still drew a random number because the condition was only on "does this key exist in the dictionary?". There was no condition on the value. I implemented this now and also created a failsafe in case a k_shelf becomes smaller than 0 (non-physical).

**Comment by ltdeck** [comment]
There still seems to be an issue in case s_sigma_rel = 0, while it works fine for s_sigma_rel > 0, see the two attached screenshot
![sigma0](https://user-images.githubusercontent.com/83716040/135724221-a15c8ffc-9bb1-4d4f-8c26-57aa24ae092e.PNG)
![sigma01](https://user-images.githubusercontent.com/83716040/135724223-d20b0145-fdf4-40fb-9d3a-776cce800fac.PNG)
s.

**Comment by bizzinho** [comment]
Unexpected behavior of 'any' created the issue. 

```
any(False)
>>> TypeError: 'bool' object is not iterable
```

numpy.any behaves as expected
```
np.any(False)
>>> False
```

Fixed and created a unit test.

**Comment by ltdeck** [comment]
Again need to reopen this; the bug persists in snowfall. Setting s_sigma_rel to 0 leads to the attached error. It does work however, for snowflake. 

Code:
from ethz_snow.snowfall import Snowfall
from ethz_snow.operatingConditions import OperatingConditions

d = {"int": 1, "ext": 1, "s0": 60, "s_sigma_rel": 0} 
S = Snowfall(k=d,Nrep=10,N_vials=(3,3,1),opcond=OperatingConditions(t_tot=1e4,cooling= {"rate": 1 / 60, "start": 20, "end": -50},holding= {"duration": 1, "temp": -12}) )

![htbug_snowfall](https://user-images.githubusercontent.com/83716040/136046203-03951c83-3807-4148-a317-d8b7dd74f8ce.PNG)

**Comment by bizzinho** [comment]
Am not able to reproduce the issue. The code works for me. Are you sure you had loaded the updated module, @ltdeck ? Maybe restart the kernel and try again. If the problem does not occur, please close again.

**Comment by ltdeck** [comment]
Indeed, I was still working with the old kernel. Restarting solved the issue.
